### PR TITLE
Created Map component and added it to available layout next to Sidebar

### PR DESCRIPTION
**Pull request by MariuszAKS**
- created Map component
- created CustomMarker component with the icon in the WZIM coloring
- to do all that used leaflef and leaflet-react

Had to add css leaflet file in order for all to work properly and had options: add file directly, access it from library or from site, went for adding the file, as I feel like it has the lowest possibility of not working under circumstances, like library update or else.

### CODE REVIEW

**Comment by MariuszAKS** [comment]
The conflict seems to just be importing Map and css file on the same line, which can be added one after the other

**Comment by MariuszAKS** [comment]
There are few more issues, will take care of them before merging

**Comment by MariuszAKS** [comment]
It should all be good, rebased branch to be complient with dev, there is double count of commits because I chose to pull when syncing, but it shouldn't be an issue, added <Map/> component under /home/map where it said that it should have the map component, when run looks like it's all working

**Review by michalmlk — APPROVED** [review]

**Comment by michalmlk** [comment]
merged to dev

**Pull request merged**
